version = 0.1
[default.global.parameters]
stack_name = "my-demo-swapi-app"

[default.deploy.parameters]
parameter_overrides = [
    "StageEnv=dev",
    "MysqlHostnameEnv=my-db-mysql.cnwbizaxdasc.us-east-1.rds.amazonaws.com",
    "MysqlUsernameEnv=admin",
    "MysqlPwdEnv=Admin123.",
    "MysqlDatabaseEnv=dbswapi",
]
s3_bucket = "mystoragebuckets3"
s3_prefix = "my-demo-swapi-app"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
