AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: "My demo deploy AWS SAM Cloud Formation"

Globals:
  Function:
    Runtime: nodejs14.x
    Architectures:
      - arm64
    MemorySize: 128
    Timeout: 30

Parameters:
  StageEnv:
    Type: String
    Default: "dev"
  MysqlHostnameEnv:
    Type: String
    Default: "my-db-mysql.cnwbizaxdasc.us-east-1.rds.amazonaws.com"
  MysqlUsernameEnv:
    Type: String
    Default: "admin"
  MysqlPwdEnv:
    Type: String
    Default: "Admin123."
  MysqlDatabaseEnv:
    Type: String
    Default: "dbswapi"

Resources:
  PeopleEndpointFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "PeopleEndpointFunction"
      Description: "Función lambda para controlar endpoints para el modulo 'people'"
      Handler: "dist/people/handler.handler"
      Environment:
        Variables:
          MYSQL_HOST: !Ref MysqlHostnameEnv
          MYSQL_USERNAME: !Ref MysqlUsernameEnv
          MYSQL_PWD: !Ref MysqlPwdEnv
          MYSQL_DATABASE: !Ref MysqlDatabaseEnv
      Events:
        AllPeople:
          Type: Api
          Properties:
            RestApiId: !Ref SwapiBasicApiGateway
            Path: /people
            Method: GET
        CreatePeople:
          Type: Api
          Properties:
            RestApiId: !Ref SwapiBasicApiGateway
            Path: /people
            Method: POST
        PeopleById:
          Type: Api
          Properties:
            RestApiId: !Ref SwapiBasicApiGateway
            Path: /people/{id}
            Method: GET
  SwapiBasicApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: "SwapiBasicApiGateway"
      StageName: !Ref StageEnv
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
