AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: "My demo deploy AWS SAM Cloud Formation"

Globals:
  Function:
    Runtime: nodejs14.x
    Architectures:
      - arm64
    MemorySize: 128
    Timeout: 30

Parameters:
  MysqlHostnameEnv:
    Type: String
    Default: "my-db-mysql.cnwbizaxdasc.us-east-1.rds.amazonaws.com"
  MysqlUsernameEnv:
    Type: String
    Default: "admin"
  MysqlPwdEnv:
    Type: String
    Default: "Admin123."
  MysqlDatabaseEnv:
    Type: String
    Default: "dbswapi"

Resources:
  MyDemoEndpointFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "MyDemoEndpointFunction"
      Description: "..."
      Handler: "dist/people/handler.handler"
      Environment:
        Variables:
          MYSQL_HOST: !Ref MysqlHostnameEnv
          MYSQL_USERNAME: !Ref MysqlUsernameEnv
          MYSQL_PWD: !Ref MysqlPwdEnv
          MYSQL_DATABASE: !Ref MysqlDatabaseEnv
      Events:
        AllExamples:
          Type: Api
          Properties:
            RestApiId: !Ref MyDemoBasicApiGateway
            Path: /examples
            Method: GET
            RequestParameters:
              - method.request.querystring.startDate: # Fecha de inicio para filtrar
                  Required: true
              - method.request.querystring.endDate: # Fecha fin para filtrar
                  Required: true
        FilterExampleByID:
          Type: Api
          Properties:
            RestApiId: !Ref MyDemoBasicApiGateway
            Path: /examples/{id}
            Method: GET
        CreateExample:
          Type: Api
          Properties:
            RestApiId: !Ref MyDemoBasicApiGateway
            Path: /examples
            Method: POST
        UpdateExample:
          Type: Api
          Properties:
            RestApiId: !Ref MyDemoBasicApiGateway
            Path: /examples/{id}
            Method: PUT
        PatchExampleById:
          Type: Api
          Properties:
            RestApiId: !Ref MyDemoBasicApiGateway
            Path: /examples/{id}
            Method: PATCH
        DeleteExample:
          Type: Api
          Properties:
            RestApiId: !Ref MyDemoBasicApiGateway
            Path: /examples/{id}
            Method: DELETE
  MyDemoBasicApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: "MyDemoBasicApiGateway"
      StageName: dev
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
